### ISSUE TITLE
Website: icon search has stopped working (Ghostery - safari - google analytics)

### ISSUE THREAD

**Issue by unikitty37** [FortAwesome/Font-Awesome#14649]
(apologies if the issue tracker is not the right place to report website problems — I can't find anything in the support area that suggests a better way, though :)

Yesterday, searching for icons worked fine. Today, search claims to have found matching results but does not show them:

![image](https://user-images.githubusercontent.com/139183/52898435-ddc54980-31d5-11e9-8333-abea006f23ae.png)

I've tried this on Safari 12.0.3 and Vivaldi 2.3.1440.48; the following error appears in the console on both. It *does* work correctly in Firefox (Developer Edition 66.0b6) though.

```
TypeError: window.cxApi.getChosenVariation is not a function. (In 'window.cxApi.getChosenVariation(e)', 'window.cxApi.getChosenVariation' is undefined)
(anonymous function) — 10.9db2b0259c1f7cbd691a.js:1:24227
shouldShowProAd — 10.9db2b0259c1f7cbd691a.js:1:24335
get — app-a1c06a8448bc5479271afe3429bc9350.js:55:25865
evaluate — app-a1c06a8448bc5479271afe3429bc9350.js:55:27014
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:55:27784
(anonymous function) — 10.9db2b0259c1f7cbd691a.js:1:25532
_render — app-a1c06a8448bc5479271afe3429bc9350.js:55:33849
r — app-a1c06a8448bc5479271afe3429bc9350.js:55:67147
get — app-a1c06a8448bc5479271afe3429bc9350.js:55:25865
hn — app-a1c06a8448bc5479271afe3429bc9350.js:55:25782
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:55:67160
init — app-a1c06a8448bc5479271afe3429bc9350.js:55:18899
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:55:55484
f — app-a1c06a8448bc5479271afe3429bc9350.js:55:55759
p — app-a1c06a8448bc5479271afe3429bc9350.js:55:56348
f — app-a1c06a8448bc5479271afe3429bc9350.js:55:55874
p — app-a1c06a8448bc5479271afe3429bc9350.js:55:56348
f — app-a1c06a8448bc5479271afe3429bc9350.js:55:55874
p — app-a1c06a8448bc5479271afe3429bc9350.js:55:56348
f — app-a1c06a8448bc5479271afe3429bc9350.js:55:55874
p — app-a1c06a8448bc5479271afe3429bc9350.js:55:56348
f — app-a1c06a8448bc5479271afe3429bc9350.js:55:55874
p — app-a1c06a8448bc5479271afe3429bc9350.js:55:56348
f — app-a1c06a8448bc5479271afe3429bc9350.js:55:55874
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:55:59897
_update — app-a1c06a8448bc5479271afe3429bc9350.js:55:32909
r — app-a1c06a8448bc5479271afe3429bc9350.js:55:67137
get — app-a1c06a8448bc5479271afe3429bc9350.js:55:25865
hn — app-a1c06a8448bc5479271afe3429bc9350.js:55:25782
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:55:67160
init — app-a1c06a8448bc5479271afe3429bc9350.js:55:18899
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:55:55484
f — app-a1c06a8448bc5479271afe3429bc9350.js:55:55759
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:55:59897
_update — app-a1c06a8448bc5479271afe3429bc9350.js:55:32909
r — app-a1c06a8448bc5479271afe3429bc9350.js:55:67137
get — app-a1c06a8448bc5479271afe3429bc9350.js:55:25865
hn — app-a1c06a8448bc5479271afe3429bc9350.js:55:25782
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:55:67160
init — app-a1c06a8448bc5479271afe3429bc9350.js:55:18899
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:55:55484
f — app-a1c06a8448bc5479271afe3429bc9350.js:55:55759
p — app-a1c06a8448bc5479271afe3429bc9350.js:55:56348
f — app-a1c06a8448bc5479271afe3429bc9350.js:55:55874
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:55:60165
_update — app-a1c06a8448bc5479271afe3429bc9350.js:55:32909
r — app-a1c06a8448bc5479271afe3429bc9350.js:55:67137
get — app-a1c06a8448bc5479271afe3429bc9350.js:55:25865
hn — app-a1c06a8448bc5479271afe3429bc9350.js:55:25782
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:55:67160
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:60:71493
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:28:15844
forEach
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:28:15830
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:28:17396
r — app-a1c06a8448bc5479271afe3429bc9350.js:28:13748
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:28:13775
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:28:16892
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:28:17085
(anonymous function) — 10.9db2b0259c1f7cbd691a.js:1:28144
_ — app-a1c06a8448bc5479271afe3429bc9350.js:35:435109
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:35:434894
i — app-a1c06a8448bc5479271afe3429bc9350.js:1:4335
c — app-a1c06a8448bc5479271afe3429bc9350.js:1:4534
promiseReactionJob
Ue — app-a1c06a8448bc5479271afe3429bc9350.js:55:11343
Be — app-a1c06a8448bc5479271afe3429bc9350.js:55:11256
qe — app-a1c06a8448bc5479271afe3429bc9350.js:55:10951
_render — app-a1c06a8448bc5479271afe3429bc9350.js:55:33894
r — app-a1c06a8448bc5479271afe3429bc9350.js:55:67147
get — app-a1c06a8448bc5479271afe3429bc9350.js:55:25865
hn — app-a1c06a8448bc5479271afe3429bc9350.js:55:25782
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:55:67160
init — app-a1c06a8448bc5479271afe3429bc9350.js:55:18899
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:55:55484
f — app-a1c06a8448bc5479271afe3429bc9350.js:55:55759
p — app-a1c06a8448bc5479271afe3429bc9350.js:55:56348
f — app-a1c06a8448bc5479271afe3429bc9350.js:55:55874
p — app-a1c06a8448bc5479271afe3429bc9350.js:55:56348
f — app-a1c06a8448bc5479271afe3429bc9350.js:55:55874
p — app-a1c06a8448bc5479271afe3429bc9350.js:55:56348
f — app-a1c06a8448bc5479271afe3429bc9350.js:55:55874
p — app-a1c06a8448bc5479271afe3429bc9350.js:55:56348
f — app-a1c06a8448bc5479271afe3429bc9350.js:55:55874
p — app-a1c06a8448bc5479271afe3429bc9350.js:55:56348
f — app-a1c06a8448bc5479271afe3429bc9350.js:55:55874
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:55:59897
_update — app-a1c06a8448bc5479271afe3429bc9350.js:55:32909
r — app-a1c06a8448bc5479271afe3429bc9350.js:55:67137
get — app-a1c06a8448bc5479271afe3429bc9350.js:55:25865
hn — app-a1c06a8448bc5479271afe3429bc9350.js:55:25782
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:55:67160
init — app-a1c06a8448bc5479271afe3429bc9350.js:55:18899
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:55:55484
f — app-a1c06a8448bc5479271afe3429bc9350.js:55:55759
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:55:59897
_update — app-a1c06a8448bc5479271afe3429bc9350.js:55:32909
r — app-a1c06a8448bc5479271afe3429bc9350.js:55:67137
get — app-a1c06a8448bc5479271afe3429bc9350.js:55:25865
hn — app-a1c06a8448bc5479271afe3429bc9350.js:55:25782
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:55:67160
init — app-a1c06a8448bc5479271afe3429bc9350.js:55:18899
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:55:55484
f — app-a1c06a8448bc5479271afe3429bc9350.js:55:55759
p — app-a1c06a8448bc5479271afe3429bc9350.js:55:56348
f — app-a1c06a8448bc5479271afe3429bc9350.js:55:55874
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:55:60165
_update — app-a1c06a8448bc5479271afe3429bc9350.js:55:32909
r — app-a1c06a8448bc5479271afe3429bc9350.js:55:67137
get — app-a1c06a8448bc5479271afe3429bc9350.js:55:25865
hn — app-a1c06a8448bc5479271afe3429bc9350.js:55:25782
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:55:67160
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:60:71493
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:28:15844
forEach
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:28:15830
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:28:17396
r — app-a1c06a8448bc5479271afe3429bc9350.js:28:13748
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:28:13775
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:28:16892
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:28:17085
(anonymous function) — 10.9db2b0259c1f7cbd691a.js:1:28144
_ — app-a1c06a8448bc5479271afe3429bc9350.js:35:435109
(anonymous function) — app-a1c06a8448bc5479271afe3429bc9350.js:35:434894
i — app-a1c06a8448bc5479271afe3429bc9350.js:1:4335
c — app-a1c06a8448bc5479271afe3429bc9350.js:1:4534
promiseReactionJob
Ue — app-a1c06a8448bc5479271afe3429bc9350.js:55:11343
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I cannot replicate this.

macOS 10.14.3, Safari 12.0.3

Could you please:
- retry in incognito mode
- check if there aren't other errors in the console (assets not loaded)

**Comment by unikitty37** [comment]
I was able to reproduce this in incognito mode on Safari.

Here are the errors — interestingly, the first on shows as being from https://www.google-analytics.com/cs/api.js on screen, but only copies to clipboard as "api.js" ¯\_(ツ)_/¯ 

I have to point out that, while Ghostery and uBlock Origin are installed in Safari and Vivaldi, they are also installed and running in Firefox, and appear to be blocking the exact same things

```
[Error] Failed to load resource: Could not connect to the server. (api.js, line 0)
[Error] Blocked a frame with origin "https://js.stripe.com" from accessing a frame with origin "https://fontawesome.com". Protocols, domains, and ports must match.
	Global Code (compiled.js:4452)
[Error] Blocked a frame with origin "https://js.stripe.com" from accessing a frame with origin "https://fontawesome.com". Protocols, domains, and ports must match.
	Global Code (outer.html:20)
	insertBefore
	prependTo (compiled.js:4829)
	inject (compiled.js:4835)
	inject (compiled.js:5614)
	inject (compiled.js:6385)
	init (compiled.js:6443)
	Global Code (compiled.js:7387)
[Error] SecurityError: Blocked a frame with origin "https://js.stripe.com" from accessing a cross-origin frame. Protocols, domains, and ports must match.
	(anonymous function) (ghostery-min.js:8:9377)
	Global Code (ghostery-min.js:8:10044)
[Error] TypeError: Not enough arguments
	removeEventListener (ghostery-min.js:8:9845)
	(anonymous function) (ghostery-min.js:8:9845)
```

**Comment by tagliala** [comment]
> I have to point out that, while Ghostery and uBlock Origin are installed in Safari and Vivaldi, they are also installed and running in Firefox, and appear to be blocking the exact same things

> I was able to reproduce this in incognito mode on Safari.

Are the aforementioned extensions available in incognito mode? If yes, could you please try without third-party extensions?

**Comment by unikitty37** [comment]
Thanks — it works unless I enable Ghostery. Even then, I can get it to work with Ghostery by allowing Google Analytics for the site and leaving everything else blocked.

I can confirm that enabling Google Analytics for fontawesome.com in Ghostery works outside of incognito mode, too.

The bizarre thing is that this still leaves Google Analytics blocked by uBlock Origin, and routed to 127.0.0.1 in the local DNS — so you wouldn't expect allowing it in Ghostery to make much difference!

**Comment by tagliala** [comment]
@talbs @robmadole any chance of getting the documentation work without google analytics?

**Comment by Ionaru** [comment]
I'd like to refer to #13952, a similar issue with Ghostery and Google Analytics that existed on the FA homepage.

**Comment by tagliala** [comment]
@Ionaru thanks, I wasn't able to find that issue the other day

Let's continue on #13952

**Comment by Ionaru** [comment]
Appears to be fixed as of 2019-02-24.

**Comment by tagliala** [comment]
I do not use ghostery. Closing here, but feel free to comment if it stops working again

**Comment by unikitty37** [comment]
Still failing here, I'm afraid — but I'm wondering if this is Ghostery making tweaks to the way their blocking works, and I haven't had the update yet. I'll follow up in a couple of days if it's still not working here.

**Comment by Ionaru** [comment]
My apologies, it worked on my Windows machine at home, but now that I try it again on Linux it is stil broken for me.

Some more version information:
Linux Ubuntu 18.04.2
Google Chrome 72.0.3626.119
Ghostery 8.3.1

**Comment by robmadole** [comment]
Hmm, I can't even find a Ghostery 8.3.1 for the Mac. Can you double-check the version @lonaru

**Comment by unikitty37** [comment]
I have Ghostery for Safari version 5.5.0 installed.

Safari lacks some of the Webkit APIs that Ghostery uses, meaning Ghostery didn't release version 7 and up for Safari.

Ghostery Lite (the App Store version) is *too* lite — the per-site controls now only allow you to enable or disable whole categories, rather than individual trackers. Until they fix that, many people are sticking with the old 5.5 — myself included.

5.5 is available from https://safari-extensions.apple.com/extensions/com.betteradvertising.ghostery-HPY23A294X/Ghostery.safariextz if anybody needs to grab a copy.

**Comment by Ionaru** [comment]
@robmadole double checked:

![image](https://user-images.githubusercontent.com/3472373/53911412-9e607f00-4056-11e9-8acc-4f24f800e6ec.png)

**Comment by tagliala** [comment]
I'm able to reproduce

Ghostery 8.3.1 / Chrome 72.0.3626.121 / Windows 10

![image](https://user-images.githubusercontent.com/556268/53911869-f77ce280-4057-11e9-9666-417c2ecd9d78.png)
